version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "18081:80"
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: 10.0.4.2:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootroot
      WORDPRESS_DB_NAME: wordpress

networks:
  wordpress:
    driver: bridge
