version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "18081:80"
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: 172.17.0.1:13306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootroot
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini


networks:
  wordpress:
    driver: bridge
