version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
