version: "3.7"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      TZ: Asia/Shanghai
    volumes:
      - ./zookeeper:/bitnami/zookeeper
    networks:
      - zk-kafka

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      # 配置broker id
      - KAFKA_BROKER_ID=1
      # 配置监听者的安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      # 定义Kafka Broker的Listener的配置项，配置外部访问和内部访问
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,OUTSIDE://:9092
      # 将Broker的Listener信息发布到Zookeeper中，供Clients（Producer/Consumer）使用
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,OUTSIDE://124.222.245.253:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # 全局消息过期时间
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      - Tz=Asia/Shanghai
    volumes:
      ## 挂载位置（kafka镜像和宿主机器之间时间保持一直）
      - /etc/localtime:/etc/localtime
      - ./kafka:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - zk-kafka
networks:
  zk-kafka:
    driver: bridge
