version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch_7.0
    image: elasticsearch:${STACK_VERSION}
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./es/data:/usr/share/elasticsearch/data #数据文件挂载
      - ./es/log:/usr/share/elasticsearch/logs #es 日志挂载
    ports:
      - ${ES_PORT}:9200
    restart: always
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - TZ=Asia/Shanghai
      - cluster.name=${CLUSTER_NAME} #设置集群名称为elasticsearch
      - discovery.type=single-node #以单一节点模式启动
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m #设置使用jvm内存大小
    networks:
      - es-kibana-single

  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana_7.0
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:19200 #设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - elasticsearch.hosts=http://elasticsearch:19200
    mem_limit: ${MEM_LIMIT}
    networks:
      - es-kibana-single


networks:
  es-kibana-single:
    driver: bridge
      #  ik 分词器的安装

      # 集群 docker-compose exec elasticsearch elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.4/elasticsearch-analysis-ik-7.17.4.zip
      # 单点 bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.4/elasticsearch-analysis-ik-7.17.4.zip
