version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:7.17.4
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./es/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
    container_name: elasticsearch
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m" #设置使用jvm内存大小
    networks:
      - es-kibana
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 4096M

  kibana:
    image: kibana:7.17.4
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 #设置访问elasticsearch的地址
      - I18N_LOCALE=zh-CN
      - "TZ=Asia/Shanghai"
    networks:
      - es-kibana
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M

networks:
  es-kibana:
    driver: bridge
      #  ik 分词器的安装

      # 集群 docker-compose exec elasticsearch elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.4/elasticsearch-analysis-ik-7.17.4.zip
      # 单点 bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.17.4/elasticsearch-analysis-ik-7.17.4.zip
