version: '3.8'

services:
  namesrv:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqnamesrv
    command: sh mqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/root/logs
      - ./data/namesrv/store:/root/store
    networks:
      - rmq

  broker:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqbroker
    command: sh mqbroker -c /opt/rocketmq/broker.conf
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      - JVM_OPTS=-Duser.home=/opt/rocketmq
      - BROKER_NAME=MyBroker
    volumes:
      - ./data/broker/logs:/opt/rocketmq/logs
      - ./data/broker/store:/opt/rocketmq/store
      - ./data/broker/config/broker.conf:/opt/rocketmq/conf/broker.conf
    networks:
      - rmq

networks:
  rmq:
    driver: bridge
