version: '3.5'
services:
  pg-master:
    image: bitnami/postgresql-repmgr:${STACK_VERSION}
    ports:
      - ${PG_POOR_PORT_MASTER}:5432
    volumes:
      - ./pg_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${PG_USERNAME} # 自定义数据库用户名称
      - POSTGRESQL_POSTGRES_PASSWORD=${PG_PASSWORD} # 对应postgres用户的密码
      - POSTGRESQL_PASSWORD=${PG_PASSWORD} # 自定义数据库用户密码
      - POSTGRESQL_DATABASE=ha # 初始化数据库
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1 # replicas数量，你可以启动多个replica，跟nodes保持一致
      - REPMGR_PRIMARY_HOST=pg-master # 主数据库
      - REPMGR_PARTNER_NODES=pg-salve,pg-master # 集群中数据库的节点
      - REPMGR_NODE_NAME=pg-0 # 集群中数据库的标识
      - REPMGR_NODE_NETWORK_NAME=pg-master # 集群中数据库的网络标识
      - REPMGR_USERNAME=${REPMGR_USERNAME} # 做数据备份用的用户，这个image自带的，如果需要修改，需要修改pg_hba.conf，然后创建一个新的用户
      - REPMGR_PASSWORD=${REPMGR_PASSWORD} # 备份数据用户的密码，同上。
    networks:
        - postgres-cluster
  pg-salve:
    image: bitnami/postgresql-repmgr:${STACK_VERSION}
    ports:
      - ${PG_POOR_PORT_SLAVE}:5432
    volumes:
      - ./pg_salve_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${PG_USERNAME} # 自定义数据库用户名称
      - POSTGRESQL_POSTGRES_PASSWORD=${PG_PASSWORD} # 对应postgres用户的密码
      - POSTGRESQL_PASSWORD=${PG_PASSWORD} # 自定义数据库用户密码
      - POSTGRESQL_DATABASE=ha
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - REPMGR_PRIMARY_HOST=pg-master
      - REPMGR_PARTNER_NODES=pg-master,pg-salve
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-salve
      - REPMGR_USERNAME=${REPMGR_USERNAME} # 做数据备份用的用户，这个image自带的，如果需要修改，需要修改pg_hba.conf，然后创建一个新的用户
      - REPMGR_PASSWORD=${REPMGR_PASSWORD} # 备份数据用户的密码，同上。
    networks:
      - postgres-cluster
  pgpool:
    image: bitnami/pgpool:${PG_POOL_VERSION}
    ports:
      - ${PG_POOL_PORT}:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-master:5432,1:pg-salve:5432 #节点列表，需要加上端口
      - PGPOOL_SR_CHECK_USER=${PG_USERNAME} #用来检测节点状态的用户。
      - PGPOOL_SR_CHECK_PASSWORD=${PG_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PG_USERNAME} #postgresql的用户
      - PGPOOL_POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=admin #管理员用户
      - PGPOOL_ADMIN_PASSWORD=${PG_PASSWORD}
      - PGPOOL_ENABLE_LOAD_BALANCING=yes #有多个read的节点的时候的配置
      - PGPOOL_POSTGRES_CUSTOM_USERS=${PG_USERNAME} #应用程序中的使用的用户
      - PGPOOL_POSTGRES_CUSTOM_PASSWORDS=${PG_PASSWORD}
    healthcheck:
      test: ["CMD","/opt/bitnami/scripts/pgpool/healthcheck.sh" ] # 健康检查
      interval: 10s #检查间隔
      timeout: 5s #超时时间
      retries: 5 #检测次数，当超过检测次数的时候，如果主节点不可用，会自动切换到下一个节点，slave节点不可用的时候 会被移除。
    networks:
      - postgres-cluster

networks:
    postgres-cluster:
        driver: bridge

