version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch_8.0
    image: elasticsearch:${STACK_VERSION}
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      # - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-kibana-single
  kibana:
    container_name: kibana_8.0
    image: kibana:${STACK_VERSION}
    restart: always
    volumes:
      - ./kibana/data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - I18N_LOCALE=zh-CN
      - TZ=Asia/Shanghai
    mem_limit: ${MEM_LIMIT}
    networks:
      - es-kibana-single
networks:
  es-kibana-single:
    driver: bridge
