version: '3.8'
services:
  namesrv1:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqnamesrv1
    command: sh mqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv1/logs:/root/logs
      - ./data/namesrv1/store:/root/store
    networks:
      - rmqnet

  namesrv2:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqnamesrv2
    command: sh mqnamesrv
    ports:
      - 9877:9876
    volumes:
      - ./data/namesrv2/logs:/root/logs
      - ./data/namesrv2/store:/root/store
    networks:
      - rmqnet

  broker1:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqbroker1
    command: sh mqbroker -c /opt/rocketmq/broker.conf
    ports:
      - 10909:10909
      - 10911:10911
    environment:
      - JVM_OPTS=-Duser.home=/opt/rocketmq
    volumes:
      - ./data/broker1/logs:/opt/rocketmq/logs
      - ./data/broker1/store:/opt/rocketmq/store
      - ./data/broker1/config/broker.conf:/opt/rocketmq/conf/broker.conf
    networks:
      - rmqnet
    depends_on:
      - namesrv1
      - namesrv2
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv2
    extra_hosts:
      - "namesrv1:127.0.0.1"
      - "namesrv2:127.0.0.1"
    restart: always

  broker2:
    image: rocketmqinc/rocketmq:4.9.1
    container_name: rmqbroker2
    command: sh mqbroker -c /opt/rocketmq/broker.conf
    ports:
      - 10910:10909
      - 10912:10911
    environment:
      - JVM_OPTS=-Duser.home=/opt/rocketmq
    volumes:
      - ./data/broker2/logs:/opt/rocketmq/logs
      - ./data/broker2/store:/opt/rocketmq/store
      - ./data/broker2/config/broker.conf:/opt/rocketmq/conf/broker.conf
    networks:
      - rmqnet
    depends_on:
      - namesrv1
      - namesrv2
    links:
      - namesrv1:namesrv1
      - namesrv2:namesrv2
    extra_hosts:
      - "namesrv1:127.0.0.1"
      - "namesrv2:127.0.0.1"
    restart: always

networks:
  rmqnet:
    driver: bridge
