version: '3.2'
services:
  mysql:
    image: mysql/mysql-server:8.0.27
    restart: always
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql     # 数据挂载
      - ./config/my.cnf:/etc/my.cnf  # 自定义的 my.cnf 配置文件挂载到容器中，可以定制 MySQL 配置。
      - ./init:/docker-entrypoint-initdb.d/    # 初始化 SQL 文件挂载，适合初次启动时自动创建数据库结构或数据表。
    ports:
      - '13306:3306' #“宿主机端口号：容器内端口号”
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot"
      ADMIN_USER: "root" #当前容器用于拥有创建账号功能的数据库账号
      ADMIN_PASSWORD: "rootroot"
      TZ: "Asia/Shanghai" #解决时区问题
    command:
    -  "--max_connections=1000" # 将最大连接数设置为 1000。
    -  "--character-set-server=utf8mb4" # 设置字符集和排序规则为 utf8mb4，以支持多语言字符。
    -  "--collation-server=utf8mb4_unicode_ci"
    -  "--log-bin=mysql-bin" # 开启二进制日志，支持事务日志和恢复。
    -  "--default-authentication-plugin=mysql_native_password" #将认证插件设置为 mysql_native_password 以提高兼容性。
    - "--innodb-buffer-pool-size=1G" # 调整缓冲池大小，适当提升数据库性能
    - "--max_allowed_packet=64M" # 设置最大数据包大小，适合大数据量传输
