version: '3.7'

services:
  redis-master:
    image: redis:${REDIS_VERSION}
    container_name: redis-master
    restart: always
    ports:
      - ${REDIS_MASTER_PORT}:6379
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./master/conf/redis.conf:/etc/redis/redis.conf
      - ./master/data:/data
      - ./master/logs:/logs
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    privileged: true
    networks:
      - redis-cluster

  redis-slave1:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave1
    restart: always
    ports:
      - ${REDIS_SLAVE1_PORT}:6379
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./slave1/conf/redis.conf:/etc/redis/redis.conf
      - ./slave1/data:/data
      - ./slave1/logs:/logs
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    depends_on:
      - redis-master
    privileged: true
    networks:
      - redis-cluster

  redis-slave2:
    image: redis:${REDIS_VERSION}
    container_name: redis-slave2
    restart: always
    ports:
      - ${REDIS_SLAVE2_PORT}:6379
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 映射配置文件和数据目录
      - ./slave2/conf/redis.conf:/etc/redis/redis.conf
      - ./slave2/data:/data
      - ./slave2/logs:/logs
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    depends_on:
      - redis-master
    privileged: true
    networks:
      - redis-cluster

networks:
  redis-cluster:
    name: redis-cluster
    driver: bridge
